MENU_SECTIONS = [   {   'icon': '🍜',
        'id': 'noodles',
        'items': [   {   'description': 'sdsadsdasd',
                         'image_path': 'img/noodles/eefaf83ee60b4b2594b2699fcc6ef704_passo2.png',
                         'name': 'teste2223',
                         'price': 'R$ 1220,00'}],
        'name': 'NOODLES',
        'position': 0,
        'subsections': [   {   'description': 'Receitas autênticas passadas por gerações',
                               'items': [   {   'description': 'Caldo de shoyu temperado com molho de soja '
                                                               'tradicional, macarrão artesanal, chashu, negi, nori e '
                                                               'ovo marinado',
                                                'name': 'Lámen Shoyu',
                                                'price': 'R$ 42,00'},
                                            {   'description': 'Caldo cremoso de miso caseiro temperado, macarrão '
                                                               'artesanal, chashu, milho, negi e ovo marinado',
                                                'name': 'Lámen Miso',
                                                'price': 'R$ 44,00'},
                                            {   'description': 'Caldo claro e refinado de sal marinho, macarrão '
                                                               'delicado, chashu, negi, menma e ovo marinado',
                                                'name': 'Lámen Shio',
                                                'price': 'R$ 40,00'},
                                            {   'description': 'Caldo cremoso de osso de porco cozido por 18 horas, '
                                                               'macarrão firme, chashu, negi, nori e ovo marinado',
                                                'name': 'Lámen Tonkotsu',
                                                'price': 'R$ 46,00'}],
                               'title': 'LÁMENS TRADICIONAIS'},
                           {   'description': 'Criações exclusivas do chef',
                               'items': [   {   'description': 'Caldo picante com pasta de gergelim, carne moída '
                                                               'temperada, macarrão artesanal, pak choi e ovo marinado',
                                                'name': 'Lámen Tantanmen',
                                                'price': 'R$ 48,00'},
                                            {   'description': 'Macarrão grosso servido separadamente com caldo '
                                                               'concentrado para mergulhar, chashu, negi e ovo '
                                                               'marinado',
                                                'name': 'Lámen Tsukemen',
                                                'price': 'R$ 50,00'},
                                            {   'description': 'Caldo de legumes e algas, macarrão artesanal, tofu '
                                                               'grelhado, cogumelos, milho, negi e broto de bambu',
                                                'name': 'Lámen Vegetariano',
                                                'price': 'R$ 38,00'}],
                               'title': 'LÁMENS ESPECIAIS'},
                           {   'description': 'Personalize seu lámen',
                               'items': [   {   'description': 'Ovo cozido marinado no shoyu por 24 horas',
                                                'name': 'Ovo Cozido Marinado',
                                                'price': 'R$ 6,00'},
                                            {   'description': 'Fatias adicionais de panceta de porco refogada',
                                                'name': 'Chashu Extra',
                                                'price': 'R$ 18,00'},
                                            {   'description': 'Folhas de alga nori crocante',
                                                'name': 'Nori',
                                                'price': 'R$ 8,00'},
                                            {   'description': 'Broto de bambu fermentado',
                                                'name': 'Menma',
                                                'price': 'R$ 10,00'},
                                            {   'description': 'Cogumelos shimeji refogados',
                                                'name': 'Shimeji',
                                                'price': 'R$ 15,00'}],
                               'title': 'TOPPINGS / EXTRAS'}],
        'subtitle': 'Nossos famosos lámens tradicionais',
        'visible': True},
    {   'icon': '🍣',
        'id': 'sushi',
        'items': [   {   'description': '8 fatias de salmão fresco cortado na técnica tradicional',
                         'name': 'Sashimi Salmão',
                         'price': 'R$ 32,00'},
                     {   'description': '8 fatias de atum vermelho premium cortado à mão',
                         'name': 'Sashimi Atum',
                         'price': 'R$ 36,00'},
                     {   'description': 'Seleção do chef: salmão, atum, peixe branco e polvo - 12 peças',
                         'name': 'Combinado Sashimi',
                         'price': 'R$ 58,00'},
                     {   'description': '6 peças de nigiri de salmão sobre arroz temperado',
                         'name': 'Sushi Salmão',
                         'price': 'R$ 28,00'},
                     {   'description': '6 peças de nigiri de atum sobre arroz temperado',
                         'name': 'Sushi Atum',
                         'price': 'R$ 32,00'},
                     {   'description': '10 peças variadas: salmão, atum, camarão, polvo e peixe branco',
                         'name': 'Sushi Especial',
                         'price': 'R$ 48,00'},
                     {   'description': 'teste',
                         'image_path': 'img/sushi/463c36c0227e429caa8a44cf42b2d78e_teste.PNG',
                         'name': 'teste',
                         'price': 'R$ 1000,00'}],
        'name': 'SUSHI & SASHIMI',
        'position': 1,
        'subsections': [   {   'description': 'sdsdsa',
                               'items': [   {   'description': 'sdadasdasd',
                                                'image_path': 'img/sushi/099c299ad26d4f979450d6d428f5a68f_imagem_2025-06-09_131133753.png',
                                                'name': 'afdfsfsd',
                                                'price': 'R$ 12220,00'}],
                               'title': 'teste'}],
        'subtitle': 'Peixes frescos e cortes especiais',
        'visible': True},
    {   'icon': '🥟',
        'id': 'entradas',
        'items': [   {   'description': '6 pastéis japoneses grelhados recheados com porco e vegetais',
                         'name': 'Gyoza',
                         'price': 'R$ 18,00'},
                     {   'description': '4 rolinhos primavera crocantes com recheio de legumes',
                         'name': 'Harumaki',
                         'price': 'R$ 16,00'},
                     {   'description': 'Tofu frito em caldo de dashi com cebolinha e gengibre ralado',
                         'name': 'Agedashi Tofu',
                         'price': 'R$ 14,00'},
                     {   'description': 'Vagens de soja cozidas no vapor com sal marinho',
                         'name': 'Edamame',
                         'price': 'R$ 12,00'},
                     {   'description': 'Salada de pepino em molho agridoce com gergelim',
                         'name': 'Sunomono',
                         'price': 'R$ 10,00'},
                     {   'description': 'Polvo em fatias finas com molho ponzu e vegetables',
                         'name': 'Tako Su',
                         'price': 'R$ 22,00'}],
        'name': 'ENTRADAS',
        'position': 2,
        'subtitle': 'Aperitivos tradicionais japoneses',
        'visible': False}]